"""empty message

Revision ID: e11621148fdb
Revises: 
Create Date: 2018-11-16 22:14:11.611566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11621148fdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classify',
    sa.Column('classify_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classify_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('classify_id'),
    sa.UniqueConstraint('classify_name')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=64), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('usernext',
    sa.Column('un_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_uid', sa.Integer(), nullable=False),
    sa.Column('n_username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('un_id'),
    sa.UniqueConstraint('n_uid')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_classify_id', sa.Integer(), nullable=True),
    sa.Column('post_name', sa.String(length=64), nullable=True),
    sa.Column('poster', sa.Integer(), nullable=True),
    sa.Column('post_content', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('click_rate', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_classify_id'], ['classify.classify_id'], ),
    sa.ForeignKeyConstraint(['poster'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_to_user',
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('n_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['n_uid'], ['usernext.n_uid'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('u_id', 'n_uid')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commentor', sa.String(length=64), nullable=True),
    sa.Column('commentor_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_content', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentor_id'], ['user.u_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('user_to_user')
    op.drop_table('posts')
    op.drop_table('usernext')
    op.drop_table('user')
    op.drop_table('classify')
    # ### end Alembic commands ###
